### ISSUE TITLE
issue when switch to arm64-v8a

### ISSUE THREAD

**Issue by binglingziyu** [binglingziyu/ffmpeg-android-build#1]
hi, I tried to compile for CPU=armv7-a and it works fine! but when I switch to arm64-v8a when I do "./build_android.sh" toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-androideabi21-clang is unable to create an executable file. do you know what could it be?

@valeriandema Have you solved it？

**Comment by valeriandema** [comment]
yes, the issue was with file names, aarch64-linux-androideabi21-clang and I had to remove "eabi" from file name aarch64-linux-android21-clang.
thank you
